### ISSUE TITLE
libsaas.net down?

### ISSUE THREAD

**Issue by bastelflp** [ducksboard/libsaas#96]
http://libsaas.net and http://docs.libsaas.net/ are down or empty and do not look connected to this repository.

**Comment by parisk** [comment]
It seems that both websites are still down. Are there any updates from the maintainers on this incident?

**Comment by gene1wood** [comment]
@wulczer Are you aware these sites have been down for a year now? Is this project abandoned? Are there replacement sites?

**Comment by wulczer** [comment]
Hi there, sorry for the long wait... Almost embarrassingly long, to be honest.

I updated the [homepage](http://ducksboard.github.io/libsaas/) and [docs](http://libsaas.readthedocs.io/en/latest/) links to live ones, once again, sorry for taking so much!

**Comment by wulczer** [comment]
BTW: the project is not actively maintained anymore, which why the domains have expired and this issue lingered for far too long... But the existing code is solid and should still do the job, if you don't need any new features.

**Comment by gene1wood** [comment]
@wulczer Looks like a couple links in the docs got missed. Here's a PR to fix the final links that point to the now dead domain name : #101 

Wanna take a look at it and merge if it looks ok?
